
name: PR Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    
    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
